blank_issues_enabled: false
contact_links:
  - name: Open a discussion
    url: https://github.com/srwi/EverythingToolbar/discussions
    about: Discuss anything that is not a bug report or feature request
